### ISSUE TITLE
bug(cem-expanded-types): Imported type checker does not account for unions

### ISSUE THREAD

**Issue by maxpatiiuk** [break-stuff/cem-tools#111] opened 2024-05-03 04:33 UTC
If I have an imported type MapView:
```ts
import type MapView from "@arcgis/core/views/MapView";
```

and a property in my web component class like this:

```ts
  @property() view?: MapView;
```

The cem-expanded-types library does incorrect comparison here:

https://github.com/break-stuff/cem-tools/blob/691a720dc392b3bb22a3f1661a0cfa9b61d0ca2f/packages/expanded-types/src/cem-plugin.ts#L263

The `item.type?.text` is `MapView | undefined`, but `i.name` is `MapView` - the comparison fails to account for a union.

**Comment by break-stuff** [comment] 2024-05-03 10:35
I'm not sure I understand. What are you expecting here?

**Comment by maxpatiiuk** [comment] 2024-05-03 18:06
I am sorry, I might be misunderstanding what `cem-expanded-types` is trying to do, but my assumption was that given this code:

```ts
// types.ts
export type SomeUnion = "a" | "b";

// my-component.ts
import type { SomeUnion } from './types';
export class MyComponent extends LitElement {
  @property() someUnion?: SomeUnion;
}
```

in `custom-elements.json` I would see something like this:

```ts
  "type": {
    "text": "SomeUnion | undefined"
  },
  "expandedType": {
    "text": "'a' | 'b' | undefined"
  }
```

**Comment by break-stuff** [comment] 2024-05-07 22:31
These should be working fine. I think the issue is that types are in an NPM package and the tool currently does not resolve types in packages.

**Comment by break-stuff** [comment] 2024-05-07 22:41
Duplicate of #101

**Closed** 2024-05-14 23:06 UTC
